[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[theme.dark]
primaryColor = "#FF4B4B"
backgroundColor = "#1E1E1E"
secondaryBackgroundColor = "#262626"
textColor = "#FFFFFF"

[server]
maxUploadSize = 5
enableXsrfProtection = true
enableCORS = false